In [92]:
import numpy as np
import matplotlib as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC                        
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.preprocessing import OrdinalEncoder, StandardScaler,LabelEncoder
from sklearn.metrics import classification_report

In [99]:
#טעינת דאטה
data=pd.read_csv("./עותק של phone_purchase.csv")
#הדאטה של החיזוי
predict=pd.read_csv("./עותק של dataToPredict.csv")

In [100]:
data

     Gender  Age  Salary  PurchasePhone
0      Male   19   19000              0
1      Male   35   20000              0
2    Female   26   43000              0
3    Female   27   57000              0
4      Male   19   76000              0
..      ...  ...     ...            ...
385    Male   56   60000              1
386  Female   49   39000              1
387    Male   39   71000              0
388    Male   47   34000              1
389  Female   48   35000              1

[390 rows x 4 columns]

In [101]:
predict

   Gender  Age  Salary
0    Male   48   33000
1    Male   47   23000
2  Female   45   45000
3    Male   60   42000
4  Female   39   59000
5  Female   46   41000
6    Male   51   23000
7  Female   50   20000
8    Male   36   33000
9  Female   49   36000

In [102]:
#בדיקת ערכים חסרים
print(data.isnull().sum())
#קידוד
encoder=LabelEncoder()
data['Gender']=encoder.fit_transform(data['Gender'])
predict['Gender']=encoder.transform(predict['Gender'])

Gender           0
Age              0
Salary           0
PurchasePhone    0
dtype: int64

In [103]:

data

     Gender  Age  Salary  PurchasePhone
0         1   19   19000              0
1         1   35   20000              0
2         0   26   43000              0
3         0   27   57000              0
4         1   19   76000              0
..      ...  ...     ...            ...
385       1   56   60000              1
386       0   49   39000              1
387       1   39   71000              0
388       1   47   34000              1
389       0   48   35000              1

[390 rows x 4 columns]

In [104]:
predict

   Gender  Age  Salary
0       1   48   33000
1       1   47   23000
2       0   45   45000
3       1   60   42000
4       0   39   59000
5       0   46   41000
6       1   51   23000
7       0   50   20000
8       1   36   33000
9       0   49   36000

In [105]:
#נרמול
scaler=StandardScaler()
data[['Age','Salary']]=scaler.fit_transform(data[['Age','Salary']])
predict[['Age','Salary']]=scaler.transform(predict[['Age','Salary']])
data

     Gender       Age    Salary  PurchasePhone
0         1 -1.762954 -1.518702              0
1         1 -0.231018 -1.489282              0
2         0 -1.092732 -0.812610              0
3         0 -0.996986 -0.400723              0
4         1 -1.762954  0.158267              0
..      ...       ...       ...            ...
385       1  1.779648 -0.312461              1
386       0  1.109426 -0.930292              1
387       1  0.151966  0.011165              0
388       1  0.917934 -1.077394              1
389       0  1.013680 -1.047974              1

[390 rows x 4 columns]

In [107]:
predict

   Gender       Age    Salary
0       1  1.013680 -1.106815
1       1  0.917934 -1.401020
2       0  0.726442 -0.753769
3       1  2.162632 -0.842030
4       0  0.151966 -0.341881
5       0  0.822188 -0.871451
6       1  1.300918 -1.401020
7       0  1.205172 -1.489282
8       1 -0.135272 -1.106815
9       0  1.109426 -1.018553

In [108]:
#פיצול נתונים
X=data[['Gender','Age','Salary']]
y=data['PurchasePhone']
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.25, random_state=42)

In [109]:
#אימון המודלים

#מודל רגרסיה לוגיסטית
logisticModel=LogisticRegression()
logisticModel.fit(X_train,y_train)

#מודל SVM
svmModel=SVC()
svmModel.fit(X_train,y_train)

#מודל KNN
knnModel=KNeighborsClassifier()
knnModel.fit(X_train,y_train)

KNeighborsClassifier()

In [110]:
models = {'Logistic Regression': logisticModel, 'SVM': svmModel, 'kNN': knnModel}

for name, model in models.items():
    preds = model.predict(X_test)
    print(f"--- {name} ---")
    print(f"Incorrect predictions: {sum(y_test != preds)}")
    print(f"Accuracy: {accuracy_score(y_test, preds):.3f}")
    print(f"Precision: {precision_score(y_test, preds):.3f}")
    print(f"Recall: {recall_score(y_test, preds):.3f}")
    print("\n")

--- Logistic Regression ---
Incorrect predictions: 14
Accuracy: 0.857
Precision: 0.923
Recall: 0.667


--- SVM ---
Incorrect predictions: 5
Accuracy: 0.949
Precision: 0.897
Recall: 0.972


--- kNN ---
Incorrect predictions: 7
Accuracy: 0.929
Precision: 0.892
Recall: 0.917

In [112]:
X_new=predict[['Gender','Age','Salary']]

#לחזות את התוצאות של הטבלה ע"י המודלים שיצרנו קודם
print(logisticModel.predict(X_new))
print(svmModel.predict(X_new))
print(knnModel.predict(X_new))

[0 0 0 1 0 0 0 0 0 0]
[1 1 0 1 0 1 1 1 0 1]
[1 1 1 1 0 1 1 1 0 1]